name: dblstd-action
author: "Zikani Nyirenda Mwase <zikani.nmwase@ymail.com>"
description: Runs dblstd to verify that the repo conforms to some standard structure
inputs:
  shapeFile:
    required: true
    description: Path or URL to the shape file
    default: './.dblstd'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v2
      with:
        stable: true
        go-version: 1.19.x
    - run: |
        git clone https://github.com/sethbonnie/dblstd dblstd-src
        cd ./dblstd-src
        go build -o dblstd . && chmod +x ./dblstd
        cd ..
        ./dblstd-src/dblstd -s "${{ inputs.shapeFile }}" .
      shell: bash
